#PBS -N FastTree
#PBS -l nodes=1:ppn=1
#PBS -l mem=5gb
#PBS -l walltime=1:00:00
#PBS -q microcluster
#PBS -o 00_log/04e_FstTr.out
#PBS -e 00_log/04e_FstTr.err

cd $PBS_O_WORKDIR

module load fasttree/2.1.7

FastTree ${input} > ${output}

## Run Log:
## qsub -v input=03_Concatenated_Tree/Srube_All_Ess_Aln.cat.fa,output=03_Concatenated_Tree/Srube_All_Ess_Aln.cat.fa.FastTree.nwk ../00_PBS/04e_FastTree.pbs
