#PBS -N Clustal_Omega
#PBS -l nodes=1:ppn=2
#PBS -l mem=5gb
#PBS -l walltime=1:00:00
#PBS -q microcluster
#PBS -o 00_log/02_${id}_ClustO.out
#PBS -e 00_log/02_${id}_ClustO.err

cd $PBS_O_WORKDIR

if [ ! -d 00_log ]; then mkdir 00_log; fi

module load argtable/2.13 clustal-omega/1.2.1

clustalo --threads 2 -i ${input} -o ${output}


## To Run
## qsub -v id=rpoB_set01,input=rpoB_set01.fasta,output=rpoB_set01.fasta.aln 00_PBS/00_Align_longSequences_ClustalOmega.pbs
